### ISSUE TITLE
Removes doublons in health report data

### ISSUE THREAD

**Issue by atuleu** [doctor-home/doctor_at_home_backend#10]
Health report testdata contains a lot of doublons, i.e. lines with the same timestamp and patientID, but different health data.

Of course its makes ugly curves in the frontend. 

It coudl also be solve in the frontedn, but the backend shoudln't store the multiple datapoint in the first place.

**Comment by idaShobs** [comment]
I will set a compound unique index on both (timestamp and patientId). But @florian-burg would need to drop the data already stored in the cloud database collection for health-report. I could also start a one time job that drops the whole collections.

 For the case of doublons from the csv files, it is a little bit more complicated to handle the doublons in csv data, because i can't handle single exceptions that occur during a write job of one csv file. It either succeeds collectively or fails. A work around will be to remove the doublons directly from the csv file.

**Comment by florian-burg** [comment]
Dear Abidemi,

 

I’m not sure what you want me to do? I think someone else is handling the database, I wouldn’t even know where to look at.

 

Have a nice day,

Florian

 

Von: Shobayo-Eniola Abidemi <notifications@github.com>
Antworten an: doctor-home/doctor_at_home_backend <reply@reply.github.com>
Datum: Samstag, 2. Mai 2020 um 21:19
An: doctor-home/doctor_at_home_backend <doctor_at_home_backend@noreply.github.com>
Cc: "Burg, Florian" <f.burg@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [doctor-home/doctor_at_home_backend] Removes doublons in health report data (#10)

 

I will set a compound unique index on both (timestamp and patientId). But @florian-burg would need to drop the data already stored in the cloud database collection for health-report. I could also start a one time job that drops the whole collections.

For the case of doublons from the csv files, it is a little bit more complicated to handle the doublons in csv data, because i can't handle single exceptions that occur during a write job of one csv file. It either succeeds collectively or fails. A work around will be to remove the doublons directly from the csv file.

**Comment by idaShobs** [comment]
Hi Florian, 

it was a mistake. I tagged the wrong Florian but i edited the post already.
